### ISSUE TITLE
[Feature Request] Instead of overlapping the notifications, show the notifications like a list

### ISSUE THREAD

**Issue by tejHackerDEV** [SchabanBo/overlayment#5]
Hi @SchabanBo, can you tell me whether the package supports the feature where if we trigger two notifications at one single time can the notifications will appear in the list view fashion instead of overlapping the notifications on top of each other. Because with this what is happening 1st notification is not being visible as 2nd notifications is showing on top of the first one in a stack manner, so it would be great if the notifications shows in a listview manner like the below package. I was trying the Simple notification that is present in your online demo

https://www.npmjs.com/package/react-toastify

**Comment by SchabanBo** [comment]
Hi @tejHackerDEV 
This would be a nice feature to have, thanks for the suggestion.

**Comment by SchabanBo** [comment]
Added in V0.2.0
